import { z } from 'zod'

/** How fal bills the endpoint. Drives both the estimate and the final charge. */
export const pricingUnit = z.enum([
  'images',
  'seconds',
  'megapixels',
  'requests',
  'minutes',
  'characters',
])

/**
 * Where an @mention lands in the model payload. Each model decides this for
 * itself, which is what keeps adding a model out of the UI code: the mention
 * component never learns that one endpoint wants `image_url` and another wants
 * `image_urls`.
 */
/**
 * What a reference slot is for, from a closed vocabulary.
 *
 * The field name cannot carry this: `image_url` is a start frame on one endpoint
 * and the thing being edited on another, and a right-click menu offering "Use as
 * image_url" is not a menu anyone can read. Closed rather than free text so the
 * board can decide what a slot accepts without asking the catalog author to also
 * write the UI copy.
 *
 * One role per sentence the menu can say. A reference is a reference whether it
 * is a still, a clip or a take, so the media kind lives in `accepts` and not in
 * a second role that would read identically.
 */
export const referenceRole = z.enum([
  'source',
  'start-frame',
  'end-frame',
  'reference',
  'input-images',
  'style-reference',
  'driving-audio',
  'voice-sample',
  'mask',
])

export const referenceMapping = z.object({
  /** Input field that receives the reference url(s). */
  field: z.string().min(1),
  /** What the slot is for. Drives the menu item and what it will accept. */
  role: referenceRole.default('source'),
  /**
   * Media kinds this slot takes. A start frame is an image even on a video
   * model, and offering a clip for it wastes a round trip to find that out.
   */
  accepts: z
    .array(z.enum(['image', 'video', 'audio']))
    .nonempty()
    .default(['image']),
  /** Menu label, sentence case. Falls back to the role when absent. */
  label: z.string().min(1).optional(),
  /**
   * True when the endpoint refuses to run without it. Editing models often do:
   * fal answers 422 and the reason is invisible from our side, so the studio has
   * to know before it submits.
   */
  required: z.boolean().default(false),
  /** true when the field is an array of urls rather than a single one. */
  array: z.boolean().default(false),
  /** Hard cap from the model's own schema. Extra references are dropped, loudly. */
  maxCount: z.int().positive().default(1),
  /**
   * What to do with the `@label` token in the prompt text once its url has been
   * mapped. Some models read the name as a subject cue, others just see noise.
   */
  token: z.enum(['strip', 'keep-label']).default('strip'),
})

/** A single control we expose in the studio for this model. */
export const modelInput = z.object({
  name: z.string().min(1),
  type: z.enum(['string', 'integer', 'number', 'boolean', 'enum']),
  label: z.string().min(1),
  required: z.boolean().default(false),
  default: z.unknown().optional(),
  enum: z.array(z.string()).optional(),
  min: z.number().optional(),
  max: z.number().optional(),
  /** Hidden inputs are sent but never rendered, for things like safety flags. */
  hidden: z.boolean().default(false),
})

export const modelDefinition = z.object({
  endpointId: z.string().min(1),
  modality: z.enum(['image', 'video', 'audio']),
  /** Studio grouping in the picker, e.g. "Text to Image", "Editing". */
  group: z.string().min(1),
  displayName: z.string().min(1),
  description: z.string().default(''),
  /**
   * The picker card. A root-relative path, because these are generated by
   * `pnpm cards` and served from our own public directory: fal's own thumbnails
   * are screenshots at a dozen sizes, and a picker where every row looks like it
   * came from a different product is one you read instead of scan.
   */
  thumbnailUrl: z
    .string()
    .regex(/^\/[\w/-]+\.svg$/, 'expected a generated card path like /models/flux-dev.svg')
    .optional(),
  featured: z.boolean().default(false),
  sortOrder: z.int().default(0),
  pricing: z.object({
    unit: pricingUnit,
    unitPriceUsd: z.number().nonnegative(),
    /**
     * Why this number is right when fal's published prose says something else.
     * Printed next to the drift report, so a recurring false alarm is answered
     * in the file rather than rediscovered every week.
     */
    note: z.string().optional(),
  }),
  /** Multiplier applied on top of the fal price. 1 means we resell at cost. */
  creditMultiplier: z.number().positive().default(1),
  /**
   * Which input carries the prompt. Text-to-speech calls it `text`, everything
   * else so far calls it `prompt`, and the studio should not have to know which.
   */
  promptField: z.string().min(1).default('prompt'),
  inputs: z.array(modelInput).min(1),
  references: z.array(referenceMapping).default([]),
  capabilities: z
    .object({
      supportsNegativePrompt: z.boolean().default(false),
      supportsSeed: z.boolean().default(false),
      maxOutputs: z.int().positive().default(1),
    })
    // prefault, not default: the inner fields carry their own defaults, so an
    // absent `capabilities` object is parsed as `{}` and filled in from there.
    .prefault({}),
})

export type ModelDefinition = z.infer<typeof modelDefinition>
export type ModelInput = z.infer<typeof modelInput>
export type ReferenceMapping = z.infer<typeof referenceMapping>
export type ReferenceRole = z.infer<typeof referenceRole>
